using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GrapeCity.Core
{
    public enum Province
    {
        None = 0,        
        Gauteng, 
        Jalisco, 
        KhyberPakhtoonkhwa, 
        Maharastra, 
        NorthIsland, 
        VII, 
        GilgitBaltistan, 
        SL, 
        KurskOblast, 
        Banten, 
        X, 
        NW, 
        Lagos, 
        PIU, 
        KL, 
        TulaOblast, 
        ON, 
        Gan, 
        WY, 
        QC, 
        Wie, 
        VEN, 
        Slaskie, 
        TYU, 
        Sinaloa, 
        CAJ, 
        Heredia, 
        CT, 
        F, 
        Gro, 
        IrkutskOblast, 
        EastJava, 
        BE, 
        RM, 
        HB, 
        Westmorland, 
        HH, 
        MinasGerais, 
        N, 
        LA, 
        JI, 
        Bihar, 
        BRY, 
        CA, 
        PE, Vienna, 
        Alberta, 
        KIR, 
        VIC, 
        Loreto, 
        Punjab, 
        Victoria, 
        ABR, 
        SouthGyeongsang, 
        Kujawskopomorskie, 
        MAR, 
        AK, 
        Aceh, 
        Junin, 
        AU, 
        Surrey, 
        CHE, 
        Quebec, 
        LeningradOblast, 
        Jeo, 
        PNZ, 
        Antioquia, 
        AC, 
        Leinster, 
        Lima, 
        Ankara, 
        Colorado, 
        Podkarpackie, 
        L, 
        SR, 
        WesternCape, 
        EasternCape, 
        KwaZuluNatal, 
        FreeState
    }
}
